CREATE TABLE IF NOT EXISTS listings(
	id INTEGER NOT NULL PRIMARY KEY,
	source TEXT NOT NULL,
	address TEXT NOT NULL,
	link TEXT NOT NULL,
	price INTEGER NOT NULL,
	square_feet INTEGER NOT NULL,
	bed INTEGER NOT NULL,
	bath INTEGER NOT NULL,
	scrape_timestamp TIMESTAMP NOT NULL
);
